### ISSUE TITLE
[Source Request] <Kamyroll Extension>

### ISSUE THREAD

**Issue by Solovertical** [jmir1/aniyomi-extensions#1117] opened 2022-12-26 20:37 UTC
## Source website
- Name: Kamyroll 
- Link: 
- Language(s): En

## Other details
Well i don't have link but this extension is implemented in saikou and there no option to download ep, Please add this as a good replacement of Animixplay, Also if possible add studio name and latest Button.

Thanks to the staff for this wonderful app

**Comment by rollingmoai** [comment] 2022-12-28 10:27
Duplicate of #400

**Closed** 2022-12-31 15:10 UTC
